Algoritmo "semnome"

Var
   largura, altura, area, quant: real
Inicio
   escreva("Digite a Largura: ")
   leia(largura)
   escreva("Digite a Altura: ")
   leia(altura)

   quant <- exp(largura, 2) + exp(altura, 2)
   
   escreval("A Quantidade Necessária é: ", quant)
Fimalgoritmo


//Faça um algoritmo que leia a largura e altura
// de uma parede, calcule e
//mostre a área a ser pintada e a quantidade
 //de tinta necessária para o serviço,
//sabendo que cada litro de tinta pinta uma área de 2metros quadrados