Algoritmo "Soma com Procedimento - Paramentro de VALOR"

Var

   P, S, soma: inteiro
Procedimento soma(A, B: inteiro)
inicio
escreval("O Primeiro Valor é: ", A)
escreval("O Segundo Valor é: ", B)
escreval("A Soma entre ", A, " e", B, " é: ", A + B)

fimprocedimento
Inicio
  escreva("Digite o primeiro númmero: ")
  leia(P)
  escreva("Digite o segundo número: ")
  leia(S)
  
  soma(P, S)
Fimalgoritmo